# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7786b00a10d508509dd7e849111c8b07a9a14104a2958ca7170d8e245044ac0b0f0db8f2230e0381948bb30722d46093a85a05af3ecfeb8d7bfefd97ada772b

test:
  secret_key_base: 4989c98d7e33f848793de1835f2f4e894a20e2acf4abf251b4a17e6301dbc185ab056c21241159852787eee476b23a1e9db7946ca990d84e1ee2b7c9ffd2a0e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
